import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="h-full" lang="en">
      <body className={inter.className + " h-full overflow-hidden"}>
        <div className="h-full flex flex-col">
          <div className="grow overflow-y-auto">{children}</div>
          <Navbar />
        </div>
      </body>
    </html>
  );
}
