name: Deploy to Production

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: self-hosted

    steps:
    - run: |
        cd /home/actions/hacktheburgh-x
        docker compose -f compose-prod.yml down
        git fetch
        git pull
        docker compose -f compose-prod.yml up -d
